// Routes
app.use('/api/auth', require('./routes/auth'));
app.use('/api/users', require('./routes/users'));
app.use('/api/vehicles', require('./routes/vehicles'));
app.use('/api/drivers', require('./routes/drivers'));
app.use('/api/trips', require('./routes/trips'));
app.use('/api/passengers', require('./routes/passengers'));
app.use('/api/business', require('./routes/business'));
app.use('/api/bookings', require('./routes/bookings'));